language: csharp
mono:
  - latest

solution: ProtocolModern_1.7.10.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore ProtocolModern_1.7.10.sln

script:
  - xbuild /p:Configuration=Release ProtocolModern_1.7.10.sln
  - xbuild /p:Configuration=Debug ProtocolModern_1.7.10.sln

notifications:
  email:
    on_success: always
